### ISSUE TITLE
Demo application stuck in PREOPERATE_6

### ISSUE THREAD

**Issue by anla-pinetek** [rtlabs-com/i-link#6]
Hi, 

I would like to get the demo application running, but i ran into a problem that I was not able to solve.
I am using a setup with a Embedded Linux System and a MAX14819 EVKIT. I am able to build and run the stack as well as the demo application on the target, for example I can set the LEDs on the EVKIT.

Here is the problem: The stack initializes and reaches the PREOPERATE_6 status for the attached devices (verified with message 0x9A in the communication trace). All information is transferred correctly from the device (e.g., device ID, vendor ID, etc). After that, I would expect message 0x99 from the master to enter OPERATIONAL state (I have another master demo setup where I can observe this). 

However, this message does not appear so the device stays in PREOPERATE_6 and the main loop in the iolink_handler is entered without further activity (other than the timeout printing “.”). The behavior was tested with the two devices from the demo setup (Display IFM E30391 and RFID Reader IFM DTI515) as well as with one IFM proximity sensor (IF 6124). 

Is there any kind of message though the internal messaging mechanisms (iolink_app_master.app_event) that the IO link handler expects?

**Comment by elupus** [comment]
This has been solved in current version of stack.
